### ISSUE TITLE
Yolov5 shows zero accuracy after quantization

### ISSUE THREAD

**Issue by Corallo** [PINTO0309/onnx2tf#318] opened 2023-04-18 08:26 UTC
### Issue Type

Others

### onnx2tf version number

1.9.6

### onnx version number

1.13.0

### tensorflow version number

2.11.0

### Download URL for ONNX

https://mega.nz/folder/PBshwDga#KwqmDZScWLIhdqOb9sqgzg

### Parameter Replacement JSON

```json
I don't know where to get this JSON
```

### Description

1. I am trying to develop a guide about deploying a model on an edge device that needs model quantized by tensor. The quantization is the main blocking part.
2. No errors, I am using a custom yolov5 (the custom part is simply the relu activation), exported to onnx, and then converted to tflite with onnx2tf, with the command   `onnx2tf -i ./fully_trained_normal.onnx -oiqt -qt per-tensor -ioqd uint8` then I am running the [yolov5 eval script](https://github.com/ultralytics/yolov5/blob/master/val.py) `python3 val.py --weights fully_trained_normal_integer_quant.tflite `. While running the eval script on the onnx model produces a map score of ~0.44, I get 0 with the quantized model. I was wondering if you know I am doing something obviously wrong that I am not aware of.
3.  Checked the quantized model on netron, it looks all right, I tried with some of the other quantized version of the model that have both filter and bias of the convolution quantized as int8, same problem apply, I tried also to export to both int8 and uint8. Checked on this repo closed issues, didn't find similar problems.
4. To obtain a working model for the edge device 
5. I linked a mega folder with the onnx model and the tflite converted version.

Any suggestion would be appreciated :)

**Comment by PINTO0309** [comment] 2023-04-18 08:42
Duplicate of #224, #263, #269

![image](https://user-images.githubusercontent.com/33194443/232722784-264703a3-31ba-4a3d-97a8-3fc92ca76ad0.png)

**Closed by PINTO0309** 2023-04-18 08:42 UTC

**Comment by Corallo** [comment] 2023-06-21 07:45
I see, looking at those other issues, I understand it is an architecture problem that doesn't support well by design the quantization by tensor.
Do you have a suggestion about object detection model that don't have this issue with quantization by tensor?
I've seen your [model zoo](https://github.com/PINTO0309/PINTO_model_zoo#2-2d-object-detection), but there I don't see any indication of which model might have this issue
